### ISSUE TITLE
cycle through TODO/DONE?

### ISSUE THREAD

**Issue by gauteh** [lervag/wiki-ft.vim#6]
Greetings,

I noticed that I can no longer cycle through TODO/DONE on lists in the wiki. I am not sure if this was provided by this plugin.. but I sorely miss it (vim-cycle does not work with vim-speeddating). I see that this should probably be in a separate plugin (I would very much like to be able to e.g. cycle through True/False in python).

Regards, Gaute

**Comment by lervag** [comment]
This feature was never part of wiki-ft. It was a part of [wiki.vim](https://github.com/lervag/wiki.vim/), but I recently separated it into a new plugin, [lists.vim](https://github.com/lervag/lists.vim). The reason was that it was really not related to the wiki functionality, and it seemed more appropriate to provide the functionality as a separate plugin. It would also make it easier to maintain and perhaps improve the features in future updates.

**Comment by gauteh** [comment]
Great! thanks, that solves it for me!

**Comment by lervag** [comment]
Great, glad to hear it :)
