### ISSUE TITLE
Add option g:wiki_filetypes to support different filetypes

### ISSUE THREAD

**Issue by BirgerNi** [lervag/wiki-ft.vim#9]
The plugin does not work for me out of the box. Since I use `*.md` and `*.Rmd` as file extension the filetype for my wiki files is `markdown`.

The command `let g:wiki_loaded=1` does not activate the plugin for me.

The following workaround work for me:

```markdown
autocmd BufRead,BufNewFile *.Rmd set filetype=wiki
autocmd BufRead,BufNewFile *.md set filetype=wiki
```

However, an option like `g:wiki_filetypes` would feel more natural for me:

```markdown
let g:wiki_filetypes = ['wiki', 'markdown']
```

What do you think?

**Comment by lervag** [comment]
Ah, well, I never intended for this plugin to be a Markdown plugin. This plugin, wiki-ft.vim, is a very lightweight syntax plugin that I made when I migrated from Vimwiki to what became wiki.vim. Initially it was part of wiki.vim, but then I made wiki.vim filetype agnostic. wiki-ft.vim was extracted because I still use the `.wiki` extension for my own wiki and I've found that the subset of Markdown that is provided here is _sufficient_ for me for the wiki stuff.

But if you're already writing Markdown `.md` files, then I would think it is actually better to use a more dedicated filetype and syntax plugin. There are a lot of different ones out there, e.g.:

* https://github.com/vim-pandoc/vim-pandoc-syntax
* https://github.com/plasticboy/vim-markdown
* https://github.com/gabrielelana/vim-markdown
* https://github.com/tpope/vim-markdown (this is the built-in filetype/syntax plugin)

I personally use `plasticboy/vim-markdown` myself for Markdown files, although I know the pandoc version should also work well.

**Comment by BirgerNi** [comment]
Thank you for clarification. Since `yaml` header #11 are important to me I guess I have to switch to one of these options. Maybe one day also [treesitter](https://github.com/nvim-treesitter/nvim-treesitter) will be good enough to handle `markdown` syntax and folding.

**Comment by lervag** [comment]
No problem. And yes, I hope treesitter may become good enough. It is not yet, in my experience.

**Comment by lervag** [comment]
And sorry for the inconvenience, by the way. :\

**Comment by BirgerNi** [comment]
> No problem. And yes, I hope treesitter may become good enough. It is not yet, in my experience.

Same here. At least for `markdown`.
